version: "3"

services:
    # app
    trixie:
        build: .
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
        networks:
            - trixie

networks:
    trixie:
        driver: bridge
